service:
  daemon: off
  log_level: debug
  http_server: true
  http_listen: 0.0.0.0
  http_port: 2021

pipeline:
  inputs:
    - name: forward
      listen: 0.0.0.0
      port: 24224
      buffer_chunk_size: 2M
      buffer_max_size: 12M

  outputs:
    - name: file
      match: "v1_*"
      path: /tmp
      file: fluentbit-2-received.json
    - name: stdout
      match: "v1_*"
      format: json_lines
    - name: opentelemetry
      match: "v1_*"
      host: vector
      port: 4318
      logs_uri: /v1/logs
      # CRITICAL: Extract trace_id/span_id from metadata (not body)
      logs_trace_id_metadata_key: trace_id
      logs_span_id_metadata_key: span_id
      logs_severity_text_metadata_key: severity_text
      # Use 'log' field as body
      logs_body_key: log
